package teste.xml.carteira;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Classe Bean utilizada no processo para gerar arquivo XML a ser enviado para
 * determinado cliente da Fertipar. Neste processo foi utilizada a API java
 * Jaxb.<br>
 * @author desenvolvimento <br>
 * 
 * <pre>
 *         This file was generated by the JavaTM Architecture for XML
 *         Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 See &lt;a
 *         href=&quot;http://java.sun.com/xml/jaxb&quot;&gt;http://java.sun.com/xml/xb&lt;/a&gt;
 *         Any modifications to this file will be lost upon recompilation of the
 *         source schema. Generated on: 2010.06.10 at 03:56:09 PM BRT
 * <p>
 *         Java class for Itens complex type.
 * <p>
 *         The following schema fragment specifies the expected content
 *         contained within this class.
 * </pre>
 * <pre>
 * &lt;complexType name=&quot;Itens&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;cod_produto&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}long&quot;/&gt;
 *         &lt;element name=&quot;descricao_produto&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;registro_MA_produto&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;quantidade_liberada&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}double&quot;/&gt;
 *         &lt;element name=&quot;preco_unitario_real&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}double&quot;/&gt;
 *         &lt;element name=&quot;natureza_fisica&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;formulacao&quot; type=&quot;{}Formulacao&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Itens", propOrder = {"codProduto", "descricaoProduto", "registroMAProduto",
    "quantidadeLiberada", "precoUnitarioReal", "naturezaFisica", "formulacao"})
public class Itens
{

	@XmlElement(name = "cod_produto")
	protected long codProduto;
	@XmlElement(name = "descricao_produto", required = true)
	protected String descricaoProduto;
	@XmlElement(name = "registro_MA_produto", required = true)
	protected String registroMAProduto;
	@XmlElement(name = "quantidade_liberada")
	protected double quantidadeLiberada;
	@XmlElement(name = "preco_unitario_real")
	protected double precoUnitarioReal;
	@XmlElement(name = "natureza_fisica", required = true)
	protected String naturezaFisica;
	@XmlElement(required = true)
	protected List<Formulacao> formulacao;

	/**
	 * Gets the value of the codProduto property.
	 */
	public long getCodProduto ()
	{
		return codProduto;
	}

	/**
	 * Sets the value of the codProduto property.
	 */
	public void setCodProduto (long value)
	{
		this.codProduto = value;
	}

	/**
	 * Gets the value of the descricaoProduto property.
	 * @return possible object is {@link String }
	 */
	public String getDescricaoProduto ()
	{
		return descricaoProduto;
	}

	/**
	 * Sets the value of the descricaoProduto property.
	 * @param value allowed object is {@link String }
	 */
	public void setDescricaoProduto (String value)
	{
		this.descricaoProduto = value;
	}

	/**
	 * Gets the value of the registroMAProduto property.
	 * @return possible object is {@link String }
	 */
	public String getRegistroMAProduto ()
	{
		return registroMAProduto;
	}

	/**
	 * Sets the value of the registroMAProduto property.
	 * @param value allowed object is {@link String }
	 */
	public void setRegistroMAProduto (String value)
	{
		this.registroMAProduto = value;
	}

	/**
	 * Gets the value of the quantidadeLiberada property.
	 */
	public double getQuantidadeLiberada ()
	{
		return quantidadeLiberada;
	}

	/**
	 * Sets the value of the quantidadeLiberada property.
	 */
	public void setQuantidadeLiberada (double value)
	{
		this.quantidadeLiberada = value;
	}

	/**
	 * Gets the value of the precoUnitarioReal property.
	 */
	public double getPrecoUnitarioReal ()
	{
		return precoUnitarioReal;
	}

	/**
	 * Sets the value of the precoUnitarioReal property.
	 */
	public void setPrecoUnitarioReal (double value)
	{
		this.precoUnitarioReal = value;
	}

	/**
	 * Gets the value of the naturezaFisica property.
	 * @return possible object is {@link String }
	 */
	public String getNaturezaFisica ()
	{
		return naturezaFisica;
	}

	/**
	 * Sets the value of the naturezaFisica property.
	 * @param value allowed object is {@link String }
	 */
	public void setNaturezaFisica (String value)
	{
		this.naturezaFisica = value;
	}

	/**
	 * Gets the value of the formulacao property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the formulacao property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFormulacao().add(newItem);
	 * </pre>
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Formulacao }
	 */
	public List<Formulacao> getFormulacao ()
	{
		if (formulacao == null)
		{
			formulacao = new ArrayList<Formulacao>();
		}
		return this.formulacao;
	}

	/**
	 * @param formulacao the formulacao to set
	 */
	public final void setFormulacao (List<Formulacao> formulacao)
	{
		this.formulacao = formulacao;
	}

}
