package teste.xml.carteira;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Classe Bean utilizada no processo para gerar arquivo XML a ser enviado para
 * determinado cliente da Fertipar. Neste processo foi utilizada a API java
 * Jaxb.
 * @author desenvolvimento
 * 
 * <pre>
 * 
 *  This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 *  Reference Implementation, vhudson-jaxb-ri-2.2-7
 *  See &lt;a href=&quot;http://java.sun.com/xml/jaxb&quot;&gt;http://java.sun.com/xml/jaxb&lt;/a&gt;
 *  Any modifications to this file will be lost upon recompilation of the source
 *  schema.
 *  Generated on: 2010.06.10 at 03:56:09 PM BRT
 * 
 * </pre>
 * 
 * <p>
 *         Java class for Carteira complex type.
 *         <p>
 *         The following schema fragment specifies the expected content
 *         contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;Carteira&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;cgc_cnpj&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;cod_cliente&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}long&quot;/&gt;
 *         &lt;element name=&quot;razao_social_cliente&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;endereco_entrega_cliente&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;bairro_entrega_cliente&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;cidade_entrega_cliente&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;uf_entrega_entrega&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;cep_entrega_cliente&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;inscr_estadual_cliente&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;inscr_produtor_cliente&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;nro_pedido_fornecimento&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}long&quot;/&gt;
 *         &lt;element name=&quot;nro_seq_pedido&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}long&quot;/&gt;
 *         &lt;element name=&quot;ano_seq_pedido&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}long&quot;/&gt;
 *         &lt;element name=&quot;itens&quot; type=&quot;{}Itens&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Carteira", propOrder = {"cgcCnpj", "codCliente", "razaoSocialCliente",
    "enderecoEntregaCliente", "bairroEntregaCliente", "cidadeEntregaCliente", "ufEntregaEntrega",
    "cepEntregaCliente", "inscrEstadualCliente", "inscrProdutorCliente", "nroPedidoFornecimento",
    "nroSeqPedido", "anoSeqPedido", "itens"})
public class Carteira
{

	@XmlElement(name = "cgc_cnpj", required = true)
	protected String cgcCnpj;
	@XmlElement(name = "cod_cliente")
	protected long codCliente;
	@XmlElement(name = "razao_social_cliente", required = true)
	protected String razaoSocialCliente;
	@XmlElement(name = "endereco_entrega_cliente", required = true)
	protected String enderecoEntregaCliente;
	@XmlElement(name = "bairro_entrega_cliente", required = true)
	protected String bairroEntregaCliente;
	@XmlElement(name = "cidade_entrega_cliente", required = true)
	protected String cidadeEntregaCliente;
	@XmlElement(name = "uf_entrega_entrega", required = true)
	protected String ufEntregaEntrega;
	@XmlElement(name = "cep_entrega_cliente", required = true)
	protected String cepEntregaCliente;
	@XmlElement(name = "inscr_estadual_cliente", required = true)
	protected String inscrEstadualCliente;
	@XmlElement(name = "inscr_produtor_cliente", required = true)
	protected String inscrProdutorCliente;
	@XmlElement(name = "nro_pedido_fornecimento")
	protected long nroPedidoFornecimento;
	@XmlElement(name = "nro_seq_pedido")
	protected long nroSeqPedido;
	@XmlElement(name = "ano_seq_pedido")
	protected long anoSeqPedido;
	@XmlElement(required = true)
	protected List<Itens> itens;

	/**
	 * Gets the value of the cgcCnpj property.
	 * @return possible object is {@link String }
	 */
	public String getCgcCnpj ()
	{
		return cgcCnpj;
	}

	/**
	 * Sets the value of the cgcCnpj property.
	 * @param value allowed object is {@link String }
	 */
	public void setCgcCnpj (String value)
	{
		this.cgcCnpj = value;
	}

	/**
	 * Gets the value of the codCliente property.
	 */
	public long getCodCliente ()
	{
		return codCliente;
	}

	/**
	 * Sets the value of the codCliente property.
	 */
	public void setCodCliente (long value)
	{
		this.codCliente = value;
	}

	/**
	 * Gets the value of the razaoSocialCliente property.
	 * @return possible object is {@link String }
	 */
	public String getRazaoSocialCliente ()
	{
		return razaoSocialCliente;
	}

	/**
	 * Sets the value of the razaoSocialCliente property.
	 * @param value allowed object is {@link String }
	 */
	public void setRazaoSocialCliente (String value)
	{
		this.razaoSocialCliente = value;
	}

	/**
	 * Gets the value of the enderecoEntregaCliente property.
	 * @return possible object is {@link String }
	 */
	public String getEnderecoEntregaCliente ()
	{
		return enderecoEntregaCliente;
	}

	/**
	 * Sets the value of the enderecoEntregaCliente property.
	 * @param value allowed object is {@link String }
	 */
	public void setEnderecoEntregaCliente (String value)
	{
		this.enderecoEntregaCliente = value;
	}

	/**
	 * Gets the value of the bairroEntregaCliente property.
	 * @return possible object is {@link String }
	 */
	public String getBairroEntregaCliente ()
	{
		return bairroEntregaCliente;
	}

	/**
	 * Sets the value of the bairroEntregaCliente property.
	 * @param value allowed object is {@link String }
	 */
	public void setBairroEntregaCliente (String value)
	{
		this.bairroEntregaCliente = value;
	}

	/**
	 * Gets the value of the cidadeEntregaCliente property.
	 * @return possible object is {@link String }
	 */
	public String getCidadeEntregaCliente ()
	{
		return cidadeEntregaCliente;
	}

	/**
	 * Sets the value of the cidadeEntregaCliente property.
	 * @param value allowed object is {@link String }
	 */
	public void setCidadeEntregaCliente (String value)
	{
		this.cidadeEntregaCliente = value;
	}

	/**
	 * Gets the value of the ufEntregaEntrega property.
	 * @return possible object is {@link String }
	 */
	public String getUfEntregaEntrega ()
	{
		return ufEntregaEntrega;
	}

	/**
	 * Sets the value of the ufEntregaEntrega property.
	 * @param value allowed object is {@link String }
	 */
	public void setUfEntregaEntrega (String value)
	{
		this.ufEntregaEntrega = value;
	}

	/**
	 * Gets the value of the cepEntregaCliente property.
	 * @return possible object is {@link String }
	 */
	public String getCepEntregaCliente ()
	{
		return cepEntregaCliente;
	}

	/**
	 * Sets the value of the cepEntregaCliente property.
	 * @param value allowed object is {@link String }
	 */
	public void setCepEntregaCliente (String value)
	{
		this.cepEntregaCliente = value;
	}

	/**
	 * Gets the value of the inscrEstadualCliente property.
	 * @return possible object is {@link String }
	 */
	public String getInscrEstadualCliente ()
	{
		return inscrEstadualCliente;
	}

	/**
	 * Sets the value of the inscrEstadualCliente property.
	 * @param value allowed object is {@link String }
	 */
	public void setInscrEstadualCliente (String value)
	{
		this.inscrEstadualCliente = value;
	}

	/**
	 * Gets the value of the inscrProdutorCliente property.
	 * @return possible object is {@link String }
	 */
	public String getInscrProdutorCliente ()
	{
		return inscrProdutorCliente;
	}

	/**
	 * Sets the value of the inscrProdutorCliente property.
	 * @param value allowed object is {@link String }
	 */
	public void setInscrProdutorCliente (String value)
	{
		this.inscrProdutorCliente = value;
	}

	/**
	 * Gets the value of the nroPedidoFornecimento property.
	 */
	public long getNroPedidoFornecimento ()
	{
		return nroPedidoFornecimento;
	}

	/**
	 * Sets the value of the nroPedidoFornecimento property.
	 */
	public void setNroPedidoFornecimento (long value)
	{
		this.nroPedidoFornecimento = value;
	}

	/**
	 * Gets the value of the nroSeqPedido property.
	 */
	public long getNroSeqPedido ()
	{
		return nroSeqPedido;
	}

	/**
	 * Sets the value of the nroSeqPedido property.
	 */
	public void setNroSeqPedido (long value)
	{
		this.nroSeqPedido = value;
	}

	/**
	 * Gets the value of the anoSeqPedido property.
	 */
	public long getAnoSeqPedido ()
	{
		return anoSeqPedido;
	}

	/**
	 * Sets the value of the anoSeqPedido property.
	 */
	public void setAnoSeqPedido (long value)
	{
		this.anoSeqPedido = value;
	}

	/**
	 * Gets the value of the itens property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the itens property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getItens().add(newItem);
	 * </pre>
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Itens }
	 */
	public List<Itens> getItens ()
	{
		if (itens == null)
		{
			itens = new ArrayList<Itens>();
		}
		return this.itens;
	}

	/**
	 * @param itens the itens to set
	 */
	public final void setItens (List<Itens> itens)
	{
		this.itens = itens;
	}

}
